spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahmadda?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ahmadda
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        detector:
          enabled: true
    hibernate:
      ddl-auto: validate

  cloud:
    aws:
      s3:
        region: ${aws.dev.s3.region}

jwt:
  access:
    secret-key: ${jwt.dev.access.secret-key}
    expiration: ${jwt.dev.access.expiration}
  refresh:
    secret-key: ${jwt.dev.refresh.secret-key}
    expiration: ${jwt.dev.refresh.expiration}

cookie:
  refresh-token:
    path: /
    domain: .ahmadda.com
    same-site: None
    secure: true
    http-only: true
    ttl: 14d

cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
    - https://ahmadda.com
    - https://dev.ahmadda.com
    - https://staging.ahmadda.com
    - http://local.ahmadda.com:5173
    - http://192.168.*:5173

notification:
  redirect-url-prefix: https://staging.ahmadda.com/

aws:
  s3:
    bucket: ${aws.dev.s3.bucket}
    folder: ${aws.dev.s3.folder}
